import React from "react";
import { Article, Section } from "../../components";
import PopUpLink from "./PopUpLink/index.js";
import SlideLink from "./SlideLink/index.js";
import BackslideLink from "./BackslideLink/index.js";

const Links = ({ active, className, style }) => (
  <Section id="Links" active={active}>
    <Article id="PopUpLinks" title="Pop Up">
      <p>
        For a number of years now, work has been proceeding in order to bring perfection to the crudely
        conceived idea of a transmission that would not only supply inverse <PopUpLink>reactive current</PopUpLink> for
        use in unilateral <PopUpLink>phase detractors</PopUpLink>, but would also be capable of automatically
        synchronizing <PopUpLink>cardinal grammeters</PopUpLink>. Such an instrument is the <PopUpLink>turbo encabulator</PopUpLink>.
      </p>
    </Article>
    <Article id="SlideLinks" title="Slide">
      <p>
        Now basically the only new principle involved is that instead of power being generated by the relative
        motion of <SlideLink>conductors</SlideLink> and <SlideLink>fluxes</SlideLink>, it is produced by the <SlideLink>modial
        interaction</SlideLink> of <SlideLink>magneto-reluctance</SlideLink> and <SlideLink>capacitive diractance</SlideLink>.
      </p>
    </Article>
    <Article id="BackslideLinks" title="Backslide">
      <p>
        The original machine had a base plate of <BackslideLink>pre-famulated amulite</BackslideLink> surmounted
        by a <BackslideLink>malleable logarithmic casing</BackslideLink> in such a way that the two <BackslideLink>spurving
        bearings</BackslideLink> were in a direct line with the <BackslideLink>panametric fan</BackslideLink>. The latter
        consisted simply of six <BackslideLink>hydrocoptic marzlevanes</BackslideLink>, so fitted to the <BackslideLink>ambifacient
        lunar waneshaft</BackslideLink> that side fumbling was effectively prevented.
      </p>
    </Article>
  </Section>
);

export default Links;
