import React from "react";
import { Article, Section } from "../../components";
import Link1 from "./Link1/index.js";
import Link2 from "./Link2/index.js";
import Link3 from "./Link3/index.js";

const Links = ({ active, className, style }) => (
  <Section id="Links" active={active}>
    <Article id="Link_1" title="Pop Up">
      <p>
        For a number of years now, work has been proceeding in order to bring perfection to the crudely
        conceived idea of a transmission that would not only supply inverse <Link1>reactive current</Link1> for
        use in unilateral <Link1>phase detractors</Link1>, but would also be capable of automatically
        synchronizing <Link1>cardinal grammeters</Link1>. Such an instrument is the <Link1>turbo encabulator</Link1>.
      </p>
    </Article>
    <Article id="Link_2" title="Slide">
      <p>
        Now basically the only new principle involved is that instead of power being generated by the relative
        motion of <Link2>conductors</Link2> and <Link2>fluxes</Link2>, it is produced by the <Link2>modial
        interaction</Link2> of <Link2>magneto-reluctance</Link2> and <Link2>capacitive diractance</Link2>.
      </p>
    </Article>
    <Article id="Link_3" title="Backslide">
      <p>
        The original machine had a base plate of <Link3>pre-famulated amulite</Link3> surmounted
        by a <Link3>malleable logarithmic casing</Link3> in such a way that the two <Link3>spurving
        bearings</Link3> were in a direct line with the <Link3>panametric fan</Link3>. The latter
        consisted simply of six <Link3>hydrocoptic marzlevanes</Link3>, so fitted to the <Link3>ambifacient
        lunar waneshaft</Link3> that side fumbling was effectively prevented.
      </p>
    </Article>
  </Section>
);

export default Links;
